name: native_ar_viewer
description: A flutter plugin to quickly view 3D models in AR in Flutter using Android SCENE VIEW and IOS QUICK LOOK.
version: 0.0.1
homepage: https://github.com/sikandernoori/native_ar_viewer

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hunaindev.native_ar_viewer
        pluginClass: NativeArViewerPlugin
      ios:
        pluginClass: NativeArViewerPlugin
